version: '3'

services:
  api_server:
    image: api_server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - '.private:/data/db'
networks:
  mern-app:
    driver: bridge


